/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

import static Jframe.DBconnection.con;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.*;


/**
 *
 * @author maini
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form signUp
     */
    public Login() {
        initComponents();
    }
    
    
    //validation
    public boolean validateLogin(){
        String name = txt_username.getText();
        String pwd = txt_password.getText();
        
        if (name.equals("")){
        JOptionPane.showMessageDialog(this,"Please Enter username");
        return false;
        
        }
        if (pwd.equals("")){
        JOptionPane.showMessageDialog(this,"Please Enter password");
        return false;
        
        }
        return true;
    }
    
    //verify creds
    public void login(){
        String name = txt_username.getText();
        String pwd = txt_password.getText();
        try{
         Class.forName("com.mysql.cj.jdbc.Driver");
         con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","");
          PreparedStatement pst = con.prepareStatement("select*from users where name = ? and password = ?");
          
          pst.setString(1,name);
          pst.setString(2,pwd);
          
        ResultSet rs = pst.executeQuery();
        if(rs.next()){
        JOptionPane.showMessageDialog(this,"login successful");
        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
        
        }else{
        JOptionPane.showMessageDialog(this,"incorrect username or password");
        }
        }catch(Exception e){
        e.printStackTrace();
        }
    }

    

    
    //check duplicate users
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel86 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel90 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel94 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel98 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel102 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel106 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel110 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel114 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel118 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabel122 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabel126 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jLabel130 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        txt_username = new app.bolivia.swing.JCTextField();
        txt_password = new app.bolivia.swing.JCTextField();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle2 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Advance Library");

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Welcome To");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/library-3.png.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Advanced Library");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(290, 290, 290)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 780));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(51, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Login Page");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 207, -1));

        jLabel8.setBackground(new java.awt.Color(51, 255, 255));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Login To Your Account");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 310, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(51, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Signup Page");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel12.setBackground(new java.awt.Color(51, 255, 255));
        jLabel12.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Create New Account Here");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField3.setBackground(new java.awt.Color(102, 102, 255));
        jTextField3.setToolTipText("Username");
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField3.setName(""); // NOI18N
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel14.setBackground(new java.awt.Color(51, 255, 255));
        jLabel14.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Username");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(51, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Signup Page");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel16.setBackground(new java.awt.Color(51, 255, 255));
        jLabel16.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Create New Account Here");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField4.setBackground(new java.awt.Color(102, 102, 255));
        jTextField4.setToolTipText("Username");
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField4.setName(""); // NOI18N
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel18.setBackground(new java.awt.Color(51, 255, 255));
        jLabel18.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Username");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(51, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Signup Page");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel20.setBackground(new java.awt.Color(51, 255, 255));
        jLabel20.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Create New Account Here");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField5.setBackground(new java.awt.Color(102, 102, 255));
        jTextField5.setToolTipText("Username");
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField5.setName(""); // NOI18N
        jPanel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel22.setBackground(new java.awt.Color(51, 255, 255));
        jLabel22.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Username");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel6.setBackground(new java.awt.Color(102, 102, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setBackground(new java.awt.Color(51, 255, 255));
        jLabel23.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Signup Page");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel24.setBackground(new java.awt.Color(51, 255, 255));
        jLabel24.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Create New Account Here");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 50, 50));

        jTextField6.setBackground(new java.awt.Color(102, 102, 255));
        jTextField6.setToolTipText("Username");
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField6.setName(""); // NOI18N
        jPanel6.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel26.setBackground(new java.awt.Color(51, 255, 255));
        jLabel26.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Username");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel7.setBackground(new java.awt.Color(102, 102, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setBackground(new java.awt.Color(51, 255, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Signup Page");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel28.setBackground(new java.awt.Color(51, 255, 255));
        jLabel28.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Create New Account Here");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField7.setBackground(new java.awt.Color(102, 102, 255));
        jTextField7.setToolTipText("Username");
        jTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField7.setName(""); // NOI18N
        jPanel7.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel30.setBackground(new java.awt.Color(51, 255, 255));
        jLabel30.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Username");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel8.setBackground(new java.awt.Color(102, 102, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setBackground(new java.awt.Color(51, 255, 255));
        jLabel31.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Signup Page");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel32.setBackground(new java.awt.Color(51, 255, 255));
        jLabel32.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Create New Account Here");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField8.setBackground(new java.awt.Color(102, 102, 255));
        jTextField8.setToolTipText("Username");
        jTextField8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField8.setName(""); // NOI18N
        jPanel8.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel34.setBackground(new java.awt.Color(51, 255, 255));
        jLabel34.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Username");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel9.setBackground(new java.awt.Color(102, 102, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setBackground(new java.awt.Color(51, 255, 255));
        jLabel35.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Signup Page");
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel36.setBackground(new java.awt.Color(51, 255, 255));
        jLabel36.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Create New Account Here");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField9.setBackground(new java.awt.Color(102, 102, 255));
        jTextField9.setToolTipText("Username");
        jTextField9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField9.setName(""); // NOI18N
        jPanel9.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel38.setBackground(new java.awt.Color(51, 255, 255));
        jLabel38.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Username");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel10.setBackground(new java.awt.Color(102, 102, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setBackground(new java.awt.Color(51, 255, 255));
        jLabel39.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Signup Page");
        jPanel10.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel40.setBackground(new java.awt.Color(51, 255, 255));
        jLabel40.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Create New Account Here");
        jPanel10.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel10.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 50, 50));

        jTextField10.setBackground(new java.awt.Color(102, 102, 255));
        jTextField10.setToolTipText("Username");
        jTextField10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField10.setName(""); // NOI18N
        jPanel10.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel42.setBackground(new java.awt.Color(51, 255, 255));
        jLabel42.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Username");
        jPanel10.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel11.setBackground(new java.awt.Color(102, 102, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setBackground(new java.awt.Color(51, 255, 255));
        jLabel43.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Signup Page");
        jPanel11.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel44.setBackground(new java.awt.Color(51, 255, 255));
        jLabel44.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Create New Account Here");
        jPanel11.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel11.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField11.setBackground(new java.awt.Color(102, 102, 255));
        jTextField11.setToolTipText("Username");
        jTextField11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField11.setName(""); // NOI18N
        jPanel11.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel46.setBackground(new java.awt.Color(51, 255, 255));
        jLabel46.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Username");
        jPanel11.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel12.setBackground(new java.awt.Color(102, 102, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setBackground(new java.awt.Color(51, 255, 255));
        jLabel47.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Signup Page");
        jPanel12.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel48.setBackground(new java.awt.Color(51, 255, 255));
        jLabel48.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Create New Account Here");
        jPanel12.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel49.setBackground(new java.awt.Color(255, 255, 255));
        jLabel49.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel12.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField12.setBackground(new java.awt.Color(102, 102, 255));
        jTextField12.setToolTipText("Username");
        jTextField12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField12.setName(""); // NOI18N
        jPanel12.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel50.setBackground(new java.awt.Color(51, 255, 255));
        jLabel50.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Username");
        jPanel12.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel13.setBackground(new java.awt.Color(102, 102, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setBackground(new java.awt.Color(51, 255, 255));
        jLabel51.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Signup Page");
        jPanel13.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel52.setBackground(new java.awt.Color(51, 255, 255));
        jLabel52.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Create New Account Here");
        jPanel13.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel53.setBackground(new java.awt.Color(255, 255, 255));
        jLabel53.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel13.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField13.setBackground(new java.awt.Color(102, 102, 255));
        jTextField13.setToolTipText("Username");
        jTextField13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField13.setName(""); // NOI18N
        jPanel13.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel54.setBackground(new java.awt.Color(51, 255, 255));
        jLabel54.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Username");
        jPanel13.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel14.setBackground(new java.awt.Color(102, 102, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setBackground(new java.awt.Color(51, 255, 255));
        jLabel55.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Signup Page");
        jPanel14.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel56.setBackground(new java.awt.Color(51, 255, 255));
        jLabel56.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Create New Account Here");
        jPanel14.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel57.setBackground(new java.awt.Color(255, 255, 255));
        jLabel57.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel14.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 50, 50));

        jTextField14.setBackground(new java.awt.Color(102, 102, 255));
        jTextField14.setToolTipText("Username");
        jTextField14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField14.setName(""); // NOI18N
        jPanel14.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel58.setBackground(new java.awt.Color(51, 255, 255));
        jLabel58.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Username");
        jPanel14.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel15.setBackground(new java.awt.Color(102, 102, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel59.setBackground(new java.awt.Color(51, 255, 255));
        jLabel59.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Signup Page");
        jPanel15.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel60.setBackground(new java.awt.Color(51, 255, 255));
        jLabel60.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Create New Account Here");
        jPanel15.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel61.setBackground(new java.awt.Color(255, 255, 255));
        jLabel61.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel15.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField15.setBackground(new java.awt.Color(102, 102, 255));
        jTextField15.setToolTipText("Username");
        jTextField15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField15.setName(""); // NOI18N
        jPanel15.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel62.setBackground(new java.awt.Color(51, 255, 255));
        jLabel62.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Username");
        jPanel15.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel16.setBackground(new java.awt.Color(102, 102, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setBackground(new java.awt.Color(51, 255, 255));
        jLabel63.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Signup Page");
        jPanel16.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel64.setBackground(new java.awt.Color(51, 255, 255));
        jLabel64.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Create New Account Here");
        jPanel16.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel65.setBackground(new java.awt.Color(255, 255, 255));
        jLabel65.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel16.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField16.setBackground(new java.awt.Color(102, 102, 255));
        jTextField16.setToolTipText("Username");
        jTextField16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField16.setName(""); // NOI18N
        jPanel16.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel66.setBackground(new java.awt.Color(51, 255, 255));
        jLabel66.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Username");
        jPanel16.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel17.setBackground(new java.awt.Color(102, 102, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel67.setBackground(new java.awt.Color(51, 255, 255));
        jLabel67.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Signup Page");
        jPanel17.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel68.setBackground(new java.awt.Color(51, 255, 255));
        jLabel68.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Create New Account Here");
        jPanel17.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel69.setBackground(new java.awt.Color(255, 255, 255));
        jLabel69.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel17.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField17.setBackground(new java.awt.Color(102, 102, 255));
        jTextField17.setToolTipText("Username");
        jTextField17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField17.setName(""); // NOI18N
        jPanel17.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel70.setBackground(new java.awt.Color(51, 255, 255));
        jLabel70.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Username");
        jPanel17.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel10.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel18.setBackground(new java.awt.Color(102, 102, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel71.setBackground(new java.awt.Color(51, 255, 255));
        jLabel71.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Signup Page");
        jPanel18.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel72.setBackground(new java.awt.Color(51, 255, 255));
        jLabel72.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Create New Account Here");
        jPanel18.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel73.setBackground(new java.awt.Color(255, 255, 255));
        jLabel73.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel18.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 50, 50));

        jTextField18.setBackground(new java.awt.Color(102, 102, 255));
        jTextField18.setToolTipText("Username");
        jTextField18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField18.setName(""); // NOI18N
        jPanel18.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel74.setBackground(new java.awt.Color(51, 255, 255));
        jLabel74.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Username");
        jPanel18.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel19.setBackground(new java.awt.Color(102, 102, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel75.setBackground(new java.awt.Color(51, 255, 255));
        jLabel75.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Signup Page");
        jPanel19.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel76.setBackground(new java.awt.Color(51, 255, 255));
        jLabel76.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("Create New Account Here");
        jPanel19.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel77.setBackground(new java.awt.Color(255, 255, 255));
        jLabel77.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel19.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField19.setBackground(new java.awt.Color(102, 102, 255));
        jTextField19.setToolTipText("Username");
        jTextField19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField19.setName(""); // NOI18N
        jPanel19.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel78.setBackground(new java.awt.Color(51, 255, 255));
        jLabel78.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("Username");
        jPanel19.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel20.setBackground(new java.awt.Color(102, 102, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel79.setBackground(new java.awt.Color(51, 255, 255));
        jLabel79.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("Signup Page");
        jPanel20.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel80.setBackground(new java.awt.Color(51, 255, 255));
        jLabel80.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Create New Account Here");
        jPanel20.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel81.setBackground(new java.awt.Color(255, 255, 255));
        jLabel81.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel20.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField20.setBackground(new java.awt.Color(102, 102, 255));
        jTextField20.setToolTipText("Username");
        jTextField20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField20.setName(""); // NOI18N
        jPanel20.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel82.setBackground(new java.awt.Color(51, 255, 255));
        jLabel82.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("Username");
        jPanel20.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel21.setBackground(new java.awt.Color(102, 102, 255));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel83.setBackground(new java.awt.Color(51, 255, 255));
        jLabel83.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("Signup Page");
        jPanel21.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel84.setBackground(new java.awt.Color(51, 255, 255));
        jLabel84.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("Create New Account Here");
        jPanel21.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel85.setBackground(new java.awt.Color(255, 255, 255));
        jLabel85.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel21.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField21.setBackground(new java.awt.Color(102, 102, 255));
        jTextField21.setToolTipText("Username");
        jTextField21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField21.setName(""); // NOI18N
        jPanel21.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel86.setBackground(new java.awt.Color(51, 255, 255));
        jLabel86.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("Username");
        jPanel21.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel18.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel22.setBackground(new java.awt.Color(102, 102, 255));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel87.setBackground(new java.awt.Color(51, 255, 255));
        jLabel87.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(255, 255, 255));
        jLabel87.setText("Signup Page");
        jPanel22.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel88.setBackground(new java.awt.Color(51, 255, 255));
        jLabel88.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(255, 255, 255));
        jLabel88.setText("Create New Account Here");
        jPanel22.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel89.setBackground(new java.awt.Color(255, 255, 255));
        jLabel89.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(255, 255, 255));
        jLabel89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel22.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 50, 50));

        jTextField22.setBackground(new java.awt.Color(102, 102, 255));
        jTextField22.setToolTipText("Username");
        jTextField22.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField22.setName(""); // NOI18N
        jPanel22.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel90.setBackground(new java.awt.Color(51, 255, 255));
        jLabel90.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(255, 255, 255));
        jLabel90.setText("Username");
        jPanel22.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel23.setBackground(new java.awt.Color(102, 102, 255));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel91.setBackground(new java.awt.Color(51, 255, 255));
        jLabel91.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(255, 255, 255));
        jLabel91.setText("Signup Page");
        jPanel23.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel92.setBackground(new java.awt.Color(51, 255, 255));
        jLabel92.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(255, 255, 255));
        jLabel92.setText("Create New Account Here");
        jPanel23.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel93.setBackground(new java.awt.Color(255, 255, 255));
        jLabel93.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(255, 255, 255));
        jLabel93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel23.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField23.setBackground(new java.awt.Color(102, 102, 255));
        jTextField23.setToolTipText("Username");
        jTextField23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField23.setName(""); // NOI18N
        jPanel23.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel94.setBackground(new java.awt.Color(51, 255, 255));
        jLabel94.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(255, 255, 255));
        jLabel94.setText("Username");
        jPanel23.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel24.setBackground(new java.awt.Color(102, 102, 255));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel95.setBackground(new java.awt.Color(51, 255, 255));
        jLabel95.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(255, 255, 255));
        jLabel95.setText("Signup Page");
        jPanel24.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel96.setBackground(new java.awt.Color(51, 255, 255));
        jLabel96.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(255, 255, 255));
        jLabel96.setText("Create New Account Here");
        jPanel24.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel97.setBackground(new java.awt.Color(255, 255, 255));
        jLabel97.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(255, 255, 255));
        jLabel97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel24.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField24.setBackground(new java.awt.Color(102, 102, 255));
        jTextField24.setToolTipText("Username");
        jTextField24.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField24.setName(""); // NOI18N
        jPanel24.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel98.setBackground(new java.awt.Color(51, 255, 255));
        jLabel98.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(255, 255, 255));
        jLabel98.setText("Username");
        jPanel24.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel25.setBackground(new java.awt.Color(102, 102, 255));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel99.setBackground(new java.awt.Color(51, 255, 255));
        jLabel99.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(255, 255, 255));
        jLabel99.setText("Signup Page");
        jPanel25.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel100.setBackground(new java.awt.Color(51, 255, 255));
        jLabel100.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(255, 255, 255));
        jLabel100.setText("Create New Account Here");
        jPanel25.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel101.setBackground(new java.awt.Color(255, 255, 255));
        jLabel101.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(255, 255, 255));
        jLabel101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel25.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField25.setBackground(new java.awt.Color(102, 102, 255));
        jTextField25.setToolTipText("Username");
        jTextField25.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField25.setName(""); // NOI18N
        jPanel25.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel102.setBackground(new java.awt.Color(51, 255, 255));
        jLabel102.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(255, 255, 255));
        jLabel102.setText("Username");
        jPanel25.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel22.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel18.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel26.setBackground(new java.awt.Color(102, 102, 255));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel103.setBackground(new java.awt.Color(51, 255, 255));
        jLabel103.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(255, 255, 255));
        jLabel103.setText("Signup Page");
        jPanel26.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel104.setBackground(new java.awt.Color(51, 255, 255));
        jLabel104.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(255, 255, 255));
        jLabel104.setText("Create New Account Here");
        jPanel26.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel105.setBackground(new java.awt.Color(255, 255, 255));
        jLabel105.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(255, 255, 255));
        jLabel105.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel26.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 50, 50));

        jTextField26.setBackground(new java.awt.Color(102, 102, 255));
        jTextField26.setToolTipText("Username");
        jTextField26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField26.setName(""); // NOI18N
        jPanel26.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel106.setBackground(new java.awt.Color(51, 255, 255));
        jLabel106.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(255, 255, 255));
        jLabel106.setText("Username");
        jPanel26.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel27.setBackground(new java.awt.Color(102, 102, 255));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel107.setBackground(new java.awt.Color(51, 255, 255));
        jLabel107.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(255, 255, 255));
        jLabel107.setText("Signup Page");
        jPanel27.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel108.setBackground(new java.awt.Color(51, 255, 255));
        jLabel108.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(255, 255, 255));
        jLabel108.setText("Create New Account Here");
        jPanel27.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel109.setBackground(new java.awt.Color(255, 255, 255));
        jLabel109.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(255, 255, 255));
        jLabel109.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel27.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField27.setBackground(new java.awt.Color(102, 102, 255));
        jTextField27.setToolTipText("Username");
        jTextField27.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField27.setName(""); // NOI18N
        jPanel27.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel110.setBackground(new java.awt.Color(51, 255, 255));
        jLabel110.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(255, 255, 255));
        jLabel110.setText("Username");
        jPanel27.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel28.setBackground(new java.awt.Color(102, 102, 255));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel111.setBackground(new java.awt.Color(51, 255, 255));
        jLabel111.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(255, 255, 255));
        jLabel111.setText("Signup Page");
        jPanel28.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel112.setBackground(new java.awt.Color(51, 255, 255));
        jLabel112.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(255, 255, 255));
        jLabel112.setText("Create New Account Here");
        jPanel28.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel113.setBackground(new java.awt.Color(255, 255, 255));
        jLabel113.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(255, 255, 255));
        jLabel113.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel28.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField28.setBackground(new java.awt.Color(102, 102, 255));
        jTextField28.setToolTipText("Username");
        jTextField28.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField28.setName(""); // NOI18N
        jPanel28.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel114.setBackground(new java.awt.Color(51, 255, 255));
        jLabel114.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(255, 255, 255));
        jLabel114.setText("Username");
        jPanel28.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel29.setBackground(new java.awt.Color(102, 102, 255));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel115.setBackground(new java.awt.Color(51, 255, 255));
        jLabel115.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(255, 255, 255));
        jLabel115.setText("Signup Page");
        jPanel29.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel116.setBackground(new java.awt.Color(51, 255, 255));
        jLabel116.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(255, 255, 255));
        jLabel116.setText("Create New Account Here");
        jPanel29.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel117.setBackground(new java.awt.Color(255, 255, 255));
        jLabel117.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel117.setForeground(new java.awt.Color(255, 255, 255));
        jLabel117.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel29.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField29.setBackground(new java.awt.Color(102, 102, 255));
        jTextField29.setToolTipText("Username");
        jTextField29.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField29.setName(""); // NOI18N
        jPanel29.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel118.setBackground(new java.awt.Color(51, 255, 255));
        jLabel118.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(255, 255, 255));
        jLabel118.setText("Username");
        jPanel29.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel28.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel26.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel30.setBackground(new java.awt.Color(102, 102, 255));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel119.setBackground(new java.awt.Color(51, 255, 255));
        jLabel119.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel119.setForeground(new java.awt.Color(255, 255, 255));
        jLabel119.setText("Signup Page");
        jPanel30.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel120.setBackground(new java.awt.Color(51, 255, 255));
        jLabel120.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel120.setForeground(new java.awt.Color(255, 255, 255));
        jLabel120.setText("Create New Account Here");
        jPanel30.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel121.setBackground(new java.awt.Color(255, 255, 255));
        jLabel121.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel121.setForeground(new java.awt.Color(255, 255, 255));
        jLabel121.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel30.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 50, 50));

        jTextField30.setBackground(new java.awt.Color(102, 102, 255));
        jTextField30.setToolTipText("Username");
        jTextField30.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField30.setName(""); // NOI18N
        jPanel30.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel122.setBackground(new java.awt.Color(51, 255, 255));
        jLabel122.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel122.setForeground(new java.awt.Color(255, 255, 255));
        jLabel122.setText("Username");
        jPanel30.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel31.setBackground(new java.awt.Color(102, 102, 255));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel123.setBackground(new java.awt.Color(51, 255, 255));
        jLabel123.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel123.setForeground(new java.awt.Color(255, 255, 255));
        jLabel123.setText("Signup Page");
        jPanel31.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel124.setBackground(new java.awt.Color(51, 255, 255));
        jLabel124.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel124.setForeground(new java.awt.Color(255, 255, 255));
        jLabel124.setText("Create New Account Here");
        jPanel31.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel125.setBackground(new java.awt.Color(255, 255, 255));
        jLabel125.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel125.setForeground(new java.awt.Color(255, 255, 255));
        jLabel125.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel31.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField31.setBackground(new java.awt.Color(102, 102, 255));
        jTextField31.setToolTipText("Username");
        jTextField31.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField31.setName(""); // NOI18N
        jPanel31.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel126.setBackground(new java.awt.Color(51, 255, 255));
        jLabel126.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel126.setForeground(new java.awt.Color(255, 255, 255));
        jLabel126.setText("Username");
        jPanel31.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel30.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel32.setBackground(new java.awt.Color(102, 102, 255));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel127.setBackground(new java.awt.Color(51, 255, 255));
        jLabel127.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel127.setForeground(new java.awt.Color(255, 255, 255));
        jLabel127.setText("Signup Page");
        jPanel32.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel128.setBackground(new java.awt.Color(51, 255, 255));
        jLabel128.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel128.setForeground(new java.awt.Color(255, 255, 255));
        jLabel128.setText("Create New Account Here");
        jPanel32.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel129.setBackground(new java.awt.Color(255, 255, 255));
        jLabel129.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel129.setForeground(new java.awt.Color(255, 255, 255));
        jLabel129.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel32.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField32.setBackground(new java.awt.Color(102, 102, 255));
        jTextField32.setToolTipText("Username");
        jTextField32.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField32.setName(""); // NOI18N
        jPanel32.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel130.setBackground(new java.awt.Color(51, 255, 255));
        jLabel130.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel130.setForeground(new java.awt.Color(255, 255, 255));
        jLabel130.setText("Username");
        jPanel32.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel33.setBackground(new java.awt.Color(102, 102, 255));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel131.setBackground(new java.awt.Color(51, 255, 255));
        jLabel131.setFont(new java.awt.Font("Segoe UI Symbol", 1, 25)); // NOI18N
        jLabel131.setForeground(new java.awt.Color(255, 255, 255));
        jLabel131.setText("Signup Page");
        jPanel33.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jLabel132.setBackground(new java.awt.Color(51, 255, 255));
        jLabel132.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel132.setForeground(new java.awt.Color(255, 255, 255));
        jLabel132.setText("Create New Account Here");
        jPanel33.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 310, -1));

        jLabel133.setBackground(new java.awt.Color(255, 255, 255));
        jLabel133.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel133.setForeground(new java.awt.Color(255, 255, 255));
        jLabel133.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel33.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 50));

        jTextField33.setBackground(new java.awt.Color(102, 102, 255));
        jTextField33.setToolTipText("Username");
        jTextField33.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField33.setName(""); // NOI18N
        jPanel33.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        jLabel134.setBackground(new java.awt.Color(51, 255, 255));
        jLabel134.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel134.setForeground(new java.awt.Color(255, 255, 255));
        jLabel134.setText("Username");
        jPanel33.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jPanel32.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel30.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel26.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel18.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jPanel2.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 540, 830));

        jLabel135.setBackground(new java.awt.Color(255, 255, 255));
        jLabel135.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel135.setForeground(new java.awt.Color(255, 255, 255));
        jLabel135.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel2.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 50, 50));

        jLabel136.setBackground(new java.awt.Color(255, 255, 255));
        jLabel136.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel136.setForeground(new java.awt.Color(255, 255, 255));
        jLabel136.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Secure_50px.png"))); // NOI18N
        jPanel2.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 50, 50));

        jLabel138.setBackground(new java.awt.Color(51, 255, 255));
        jLabel138.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel138.setForeground(new java.awt.Color(255, 255, 255));
        jLabel138.setText("Username");
        jPanel2.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, -1));

        jLabel139.setBackground(new java.awt.Color(51, 255, 255));
        jLabel139.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel139.setForeground(new java.awt.Color(255, 255, 255));
        jLabel139.setText("Password");
        jPanel2.add(jLabel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 310, 20));

        txt_username.setBackground(new java.awt.Color(102, 102, 255));
        txt_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_username.setPlaceholder("Enter Username");
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, -1));

        txt_password.setBackground(new java.awt.Color(102, 102, 255));
        txt_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_password.setPlaceholder("Enter Password");
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 220, -1));

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(51, 0, 255));
        rSMaterialButtonCircle1.setText("LOGIN");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 360, 60));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(51, 51, 51));
        rSMaterialButtonCircle2.setText("SIGNUP");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 350, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 540, 780));

        setSize(new java.awt.Dimension(1282, 793));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
      
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        
    }//GEN-LAST:event_txt_usernameFocusLost

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        
        if(validateLogin()){
            login();
        
        }
        
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private app.bolivia.swing.JCTextField txt_password;
    private app.bolivia.swing.JCTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
